dataset: "mnist"
nb_classes: 10
model:
  loss: "CEL"
  initialized: false

  layers:
    - type: "Convolutional"
      number_kernels: 8
      size_kernel: 3
      stride: 1
      padding: 1
      initialization: "he"

    - type: "Activation"
      function: "relu"

    - type: "MaxPool"
      size_kernel: 2
      stride: 2

    - type: "Convolutional"
      number_kernels: 16
      size_kernel: 3
      stride: 1
      padding: 1
      initialization: "he"

    - type: "Activation"
      function: "relu"

    - type: "MaxPool"
      size_kernel: 2
      stride: 2

    - type: "Flattening"

    - type: "Dense"
      number_neurons: 64
      initialization: "he"

    - type: "Activation"
      function: "relu"

    - type: "Dropout"
      drop_rate: 0.1

    - type: "Dense"
      number_neurons: 10

training:
  normalize: "division"
  validation_part: 0.2
  early_stop: true
  patience: 5        
  min_epoch: 8       
  epochs: 5         
  batch_size: 64
  optimizer: 
    type: "Adam"
    learning_rate: 0.001
    momentum_rate: 0.9
    velocity_rate: 0.999

visualization:
  show_plots: true
  minus_y: false

save_file: ""
CAM_image: null